// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3f0x9V-k7Sxhe7sI4RFNTWtPUWJVYck',
    appId: '1:241445299241:web:03bed2917a1529af442838',
    messagingSenderId: '241445299241',
    projectId: 'cmad-englishstudyapp',
    authDomain: 'cmad-englishstudyapp.firebaseapp.com',
    storageBucket: 'cmad-englishstudyapp.appspot.com',
    measurementId: 'G-34W3H8J210',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC54R0BoU5NMCPV4weJHzvVwA96JmzZ98E',
    appId: '1:241445299241:android:752a9ccb46e354c6442838',
    messagingSenderId: '241445299241',
    projectId: 'cmad-englishstudyapp',
    storageBucket: 'cmad-englishstudyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHOEzhjJlct0lRGSEy9X2Y-zRN3pwHK1s',
    appId: '1:241445299241:ios:9b5646492c337fec442838',
    messagingSenderId: '241445299241',
    projectId: 'cmad-englishstudyapp',
    storageBucket: 'cmad-englishstudyapp.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHOEzhjJlct0lRGSEy9X2Y-zRN3pwHK1s',
    appId: '1:241445299241:ios:f406f5128655ede7442838',
    messagingSenderId: '241445299241',
    projectId: 'cmad-englishstudyapp',
    storageBucket: 'cmad-englishstudyapp.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
