
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      MSBuild version 17.9.8+b34f75857 for .NET Framework
      Build started 5/19/2024 8:41:05 PM.
      
      Project "C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(513,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
      LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      Done Building Project "C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(513,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
      
      "C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.99
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      MSBuild version 17.9.8+b34f75857 for .NET Framework
      Build started 5/19/2024 8:41:07 PM.
      
      Project "C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(513,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
      LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      Done Building Project "C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(513,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
      
      "C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\\Users\\evilx\\AndroidStudioProjects\\CMAD\\untitled1\\windows\\CMakeFiles\\3.29.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:01.26
      
      
...
